/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
#if 0
    // initialize the registers with some value
	// load R1 to store 0x20001000 memory address
	__asm volatile("LDR R1,=#0x20001000");
	// load R2 to store 0x20001004 memory address
	__asm volatile("LDR R2,=#0x20001004");

	// memory load instruction, load into R0, from data at memory location stored in R1
	__asm volatile("LDR R0,[R1]");
	// memory load instruction, load into R1, from data at memory location stored in R2
	__asm volatile("LDR R1,[R2]");
	// add instruction, store result of addition in R0, two operand is R0 and R1
	__asm volatile("ADD R0,R0,R1");
	// store the result in R0 into the data at memory location that is stored in R2
	__asm volatile("STR R0,[R2]");
#endif
#if 0
	int val=50;
	// operand = constraint string + constraint expression
	// constraint string is r, constraint expression is val
	// got one more colon at the end, for clobber list which is empty also, can omit
	// but cannot omit the second colon, because "r"(val) will be treated as output operand
	__asm volatile("MOV R0,%0": :"r"(val):);
	// __asm volatile("MOV R0,%0": :"i"(0x50):);
#endif
#if 0
	int control_reg;
	// read CONTROL register to control_reg
	__asm volatile("MRS %0,CONTROL":"=r"(control_reg));

#endif
#if 0
	int var1=10, var2;
	__asm volatile("MOV %0,%1":"=r"(var2): "r"(var1));

#endif
	int p1, *p2;
	p2 = (int*)0x20000008;
	__asm volatile("LDR %0,[%1]":"=r"(p1): "r"(p2));

	/* Loop forever */
	for(;;);

}
