/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>

// this function executes in THREAD MODE of the processor
void generate_interrupt()
{
	uint32_t *pSTIR = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//enable IRQ3 interrupt
	*pISER0 |= (1 << 3);

	//generate an interrupt from software for IRQ3
	*pSTIR |= (3 & 0x1FF);
}

// this function (ISR) executes in HANDLER MODE of the processor
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode: ISR\n");
}

void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	// trap the code in an infinite loop
	while(1);
}

void change_access_level_unpriv()
{
	// read
	__asm volatile ("MRS R0,CONTROL");
	// modify, value after ORing of R0 and immediate value of 0x01
	// goal is to set the 0th bit to 1, then put the value pack to R0
	__asm volatile ("ORR R0,R0,#0x01");
	//write
	__asm volatile ("MSR CONTROL,R0");
}

// this function executes in THREAD MODE + Privileged access level of the processor
int main(void)
{
    /* Loop forever */
	printf("In thread mode: before interrupt\n");

	change_access_level_unpriv();

	// since now its in unprivileged access level, then means cannot run the code in
	// generate_interrupt function
	generate_interrupt();

	printf("In thread mode: before interrupt\n");

	for(;;);
}
