/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#define USART3_IRQNO 39

// USART3 ISR
// go to startup file to find the name
void USART3_IRQHandler(void)
{
	printf("in USART3 isr\n");
}

int main(void)
{
	// 1. manually pend the pending bit for the USART3 IRQ number in NVIC
	// this is 0xE000E200 + 4
	uint32_t *pISPR1 = (uint32_t*)0xE000E204;

	// modify the bit position 7 to 1 but shifting 1
	*pISPR1 |= (1 << (USART3_IRQNO % 32));

	// 2. Enable the USART3 IRQ number in NVIC
	// this is 0xE000E100 + 4
	uint32_t *pISER1 = (uint32_t*)0xE000E104;

	// modify the bit position 7 to 1 but shifting 1
	*pISER1 |= (1 << (USART3_IRQNO % 32));

	for(;;);
}
